### PR TITLE
migrate to typescript

### PR DESCRIPTION
**Pull request by phra**

### CODE REVIEW

**Comment by scopsy** [comment]
Great work!

I'll review and merge ASAP.

**Comment by phra** [comment]
you can find the final result at https://github.com/phra/await-to-ts

as you can see i've refactored the entire project. (and write tests too)

if you are interested in merging this changes in this project, we can make a quick chat on slack or else to decide how to merge the changes.

**Comment by phra** [comment]
@scopsy can you let me know something? otherwise i will proceed on my own..

**Comment by phra** [comment]
@scopsy @ComBarnea can someone say something?

**Comment by scopsy** [comment]
@phra Hey man, sorry for being not available. quite busy at work. Thanks for the pull request. it seems like you changed the library name in npm. People are using the current library name and it can break some places.

IMO we should just generate a definitions files for the current js files. It's a really small utility library (just a few lines of code) so we can simply add a .d.ts file for the main function.

What do you think ?

**Comment by phra** [comment]
hi @scopsy 
for me it's fine to merge my fork with the mainstream, but as you can see i've rewritten the examples, the readme and written the tests, so right now the two sources are very different.
how do you suggest to procede?

**Comment by phra** [comment]
@scopsy can you please ping me on [this slack](https://bolognatechscene.herokuapp.com/) so that i can talk to you without have to wait weeks between messages? thanks..

**Comment by phra** [comment]
are you alive man?

**Pull request closed without merging**
