### PR TITLE
Mention Node 7 in Readme

### PR DESCRIPTION
**Pull request by Nicholaiii**
async/await works natively in Node 7, it's a shame to at least not mention it as an option. :)

### CODE REVIEW

**Comment by ComBarnea** [comment]
Actually it works natively in Node ^7.6.0 :-)

**Comment by Nicholaiii** [comment]
@ComBarnea Of course! Thanks for pointing that out, it wouldn't seem as obvious to everyone.

**Comment by phra** [comment]
@Nicholaiii can you please send a PR also to [await-to-ts](https://github.com/phra/await-to-ts/) ?
@ComBarnea can you please give your opinion on https://github.com/scopsy/await-to-js/pull/3 ?
@scopsy seems unavailable..

**Comment by ComBarnea** [comment]
@phra sure thing :)

**Comment by Nicholaiii** [comment]
@phra [phra/await-to-ts/pull/3](https://github.com/phra/await-to-ts/pull/3)

**Comment by phra** [comment]
@Nicholaiii merging right now after a little edit. thanks.

**Comment by scopsy** [comment]
@Nicholaiii Thanks! Merged. Sorry for being unavailable, was quite busy at work.

**Pull request merged**
